import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import  requests  from '../utils/requests'

export default function Home({results}) {

  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header/>
     <Nav/> 
     <Results results={results}/>
  
    </div>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
 }`,
  
// https://api.themoviedb.org/3/movie/550?api_key=7160ce285929abcc03e09ca1941c2a0e
).then(res => res.json());
return{
  
  props: {
    results: request.results,
  } ,
};

}

